import sqlite3
con = sqlite3.connect("Game.db")
cur = con.cursor()
cur.execute("CREATE TABLE Cards(id INTEGER PRIMARY KEY,Color TEXT NOT NULL,Value TEXT NOT NULL)")
cur.execute("insert into Cards(Color,Value) values ('green','POKRĘĆ NAM DUPĄ')")
cur.execute("insert into Cards(Color,Value) values ('green','ŚCIĄGNIJ ARTYKUŁ UBRANIA PRZEZ GODZINĘ')")
cur.execute("insert into Cards(Color,Value) values ('green','POKAŻ STÓPKI')")
cur.execute("insert into Cards(Color,Value) values ('green','ZRÓB FIKOŁKA')")
cur.execute("insert into Cards(Color,Value) values ('green','JEBNIJ PIRUETA')")
cur.execute("insert into Cards(Color,Value) values ('green','WYMIEŃ JEDEN SWÓJ FETYSZ')")
cur.execute("insert into Cards(Color,Value) values ('green','CMOKNIJ OSOBĘ')")
cur.execute("insert into Cards(Color,Value) values ('green','OCEN BRUTALNIE OSOBĘ')")
cur.execute("insert into Cards(Color,Value) values ('green','USIĄDŹ KOMUŚ NA KOLANACH')")
cur.execute("insert into Cards(Color,Value) values ('green','POZWÓL ŻEBY OSOBA CIE GILGOTAŁA')")
cur.execute("insert into Cards(Color,Value) values ('green','PIERDOLNIJ OSOBĘ W DUPĘ')")
cur.execute("insert into Cards(Color,Value) values ('green','WOJNA NA KĆIUKI Z OSOBĄ')")
cur.execute("insert into Cards(Color,Value) values ('green','ZRÓB KARAOKE DO “STARSHIPS” PRZEZ NIKIMINAJ')")
cur.execute("insert into Cards(Color,Value) values ('green','ZRÓB Z KARAOKE DO RANDOMOWEJ PIOSENKI Z OSOBĄ')")
cur.execute("insert into Cards(Color,Value) values ('green','ZATAŃCZ SOLO DO RANDOMOWEJ PIOSENKI')")
cur.execute("insert into Cards(Color,Value) values ('green','ZRÓB KARAOKE DO PIOSENKI OBCEGO JĘZYKA')")
cur.execute("insert into Cards(Color,Value) values ('green','OBLEJ SIE WODĄ')")
cur.execute("insert into Cards(Color,Value) values ('green','CUDDLE PRZEZ 5M Z OSOBĄ')")
cur.execute("insert into Cards(Color,Value) values ('green','OPOWIEDZ DZIWNĄ HISTORIĘ Z ŻYCIA')")
cur.execute("insert into Cards(Color,Value) values ('green','OPOWIEDZ SUCHARA I JEŻELI KAŻDA OSOBA SIĘ ZAŚMIEJE NIE "
            "PIJ')")
cur.execute("insert into Cards(Color,Value) values ('green','PIJ XD')")
cur.execute("insert into Cards(Color,Value) values ('green','JEBNIJ JAGGER BOMBE NA RAZ')")
cur.execute("insert into Cards(Color,Value) values ('green','ZAGRAJ Z OSOBĄ W KÓŁKO I KRZYŻYK NA CZOLE INNEJ OSOBY')")
cur.execute("insert into Cards(Color,Value) values ('green','NARYSUJ SOBIE CHUJA NA CZOLE')")
cur.execute("insert into Cards(Color,Value) values ('green','WŁÓŻ SOBIE POMARAŃCZE JAKO CYCKI')")
cur.execute("insert into Cards(Color,Value) values ('green','NIE ODZYWAJ SIE PRZEZ LOSOWY CZAS')")
cur.execute("insert into Cards(Color,Value) values ('green','ROSYJSKA RULETKA Z TRZEMA INNYMI OSOBAMI')")
cur.execute("insert into Cards(Color,Value) values ('green','FUCK MARRY KILL')")
cur.execute("insert into Cards(Color,Value) values ('green','WYPIJ LITR WODY W JEDNA MINUTE')")
cur.execute("insert into Cards(Color,Value) values ('green','ZATAŃCZ WALTZ Z RANDOMOWĄ OSOBĄ')")
cur.execute("insert into Cards(Color,Value) values ('green','WPIERDOL TRAWĘ')")
cur.execute("insert into Cards(Color,Value) values ('green','WYMASUJ KOMUŚ STOPY')")
cur.execute("insert into Cards(Color,Value) values ('green','WYMASUJ KOGOŚ')")
cur.execute("insert into Cards(Color,Value) values ('green','POWIEDZ KTO MA TU MAŁEGO')")
cur.execute("insert into Cards(Color,Value) values ('green','POWIEDZ KTO TU JEST DLA CIEBIE NAJBARDZIEJ ATRAKTYWNY')")
cur.execute("insert into Cards(Color,Value) values ('green','POWIEDZ KTO MA TU KOŃSKIEGO CHUJA')")
cur.execute("insert into Cards(Color,Value) values ('green','POWIEDZ KTO TU JEST NAJWIĘKSZĄ PIZDĄ')")
cur.execute("insert into Cards(Color,Value) values ('green','POWIEDZ COS MIŁEGO O LOSOWEJ OSOBIE')")
cur.execute("insert into Cards(Color,Value) values ('green','POWIEDZ COS NIE MIŁEGO O LOSOWEJ OSOBIE')")
cur.execute("insert into Cards(Color,Value) values ('yellow','POLIŻ SIĘ Z KIMŚ PRZEZ 5 SEKUND')")
cur.execute("insert into Cards(Color,Value) values ('yellow','ŚCIĄGNIJ ARTYKUŁ UBRANIA PRZEZ GODZINĘ')")
cur.execute("insert into Cards(Color,Value) values ('yellow','ROZBIERZ SIĘ O JEDNĄ WARSTWĘ UBRAŃ')")
cur.execute("insert into Cards(Color,Value) values ('yellow','ROZBIERZ SIĘ O JEDNĄ WARSTWĘ UBRAŃ')")
cur.execute("insert into Cards(Color,Value) values ('yellow','PIJ 2 SZOTY')")
cur.execute("insert into Cards(Color,Value) values ('yellow','IMITUJ ROBIENIE LODA LOSOWEJ OSOBIE')")
cur.execute("insert into Cards(Color,Value) values ('yellow','NAPIJ SIE Z UST INNEJ OSOBY')")
cur.execute("insert into Cards(Color,Value) values ('yellow','POCAŁUJ OSOBĘ')")
cur.execute("insert into Cards(Color,Value) values ('yellow','POMACAJ OSOBIE DUPE')")
cur.execute("insert into Cards(Color,Value) values ('yellow','POLIŻ KOMUŚ TWARZ')")
cur.execute("insert into Cards(Color,Value) values ('yellow','POLIŻ KOMUŚ UCHO')")
cur.execute("insert into Cards(Color,Value) values ('yellow','POWIEDZ 3 RZECZY KTÓRE CIE PODNIECAJĄ')")
cur.execute("insert into Cards(Color,Value) values ('yellow','NAPISZ NA CZOLE “JESTEM SZMATĄ”')")
cur.execute("insert into Cards(Color,Value) values ('yellow','NAPISZ NA CZOLE “PEDAŁ”')")
cur.execute("insert into Cards(Color,Value) values ('yellow','POLIŻ KOMUŚ POLIŻ KOGOŚ CZOŁO')")
cur.execute("insert into Cards(Color,Value) values ('yellow','UDAWAJ PSA LOSOWEJ OSOBY PRZEZ GODZINĘ')")
cur.execute("insert into Cards(Color,Value) values ('yellow','POWIEDZ KTO Z GRACZY CIE NAJBARDZIEJ WKURWIA')")
cur.execute("insert into Cards(Color,Value) values ('yellow','WŁÓŻ SOBIE LÓD W BIELIZNĘ')")
cur.execute("insert into Cards(Color,Value) values ('yellow','WYBIERZ OSOBĘ KTÓRA WYKONUJE NASTĘPNĄ KARTKĘ')")
cur.execute("insert into Cards(Color,Value) values ('yellow','PRZECZYTAJ  OSTATNIA WIADOMOŚĆ KTÓRĄ DOSTAŁEŚ')")
cur.execute("insert into Cards(Color,Value) values ('yellow','POKAZ OSTATNIE 3 ZDJĘCIA Z GALERII')")
cur.execute("insert into Cards(Color,Value) values ('yellow','OTWÓRZ TWITTER/REDDIT I PRZEWIŃ TROCHĘ')")
cur.execute("insert into Cards(Color,Value) values ('yellow','KRZYKNIJ “JESTEM KURWĄ!”')")
cur.execute("insert into Cards(Color,Value) values ('yellow','POWIEDZ NAJWIĘKSZA WADE O SOBIE')")
cur.execute("insert into Cards(Color,Value) values ('yellow','POWIEDZ KOGO BYS TUTAJ PRZELECIAŁ')")
cur.execute("insert into Cards(Color,Value) values ('yellow','POWIEDZ JAKIŚ SWÓJ SEKRET')")
cur.execute("insert into Cards(Color,Value) values ('yellow','POWIEDZ KIEDY OSTATNIO SIE MYŁEŚ')")
cur.execute("insert into Cards(Color,Value) values ('yellow','POWIEDZ NAJDZIWNIEJSZĄ RZECZ/OSOBĘ DO KTÓREJ WALIŁEŚ "
            "KONIA')")
cur.execute("insert into Cards(Color,Value) values ('yellow','POWIEDZ NAJDZIWNIEJSZE MIEJSCE W KTÓRYM WALIŁEŚ KONIA')")
cur.execute("insert into Cards(Color,Value) values ('yellow','OPOWIEDZ HISTORIE O TYM JAK CIE PRZYŁAPANO PRZY DZIWNEJ "
            "SYTUACJI')")
cur.execute("insert into Cards(Color,Value) values ('yellow','ANAL CZY ORAL?')")
cur.execute("insert into Cards(Color,Value) values ('red','ZŁAP KOMUŚ KROCZE')")
cur.execute("insert into Cards(Color,Value) values ('red','POKAZ SWOJĄ HISTORIE PRZEGLĄDANIA')")
cur.execute("insert into Cards(Color,Value) values ('red','ROZBIERZ SIE O JEDNĄ WARSTWĘ UBRAŃ')")
cur.execute("insert into Cards(Color,Value) values ('red','WYPIJ SHOTA TEQUILI/ALKO Z KOGOŚ PĘPKA')")
cur.execute("insert into Cards(Color,Value) values ('red','NAPIJ SIE SZOTA TEQUILI/ALKO Z PĘPKA LOSOWEJ OSOBY')")
cur.execute("insert into Cards(Color,Value) values ('red','ZRÓB LOSOWEJ OSOBIE SENSUALNY MASAŻ PRZEZ MINUTE')")
cur.execute("insert into Cards(Color,Value) values ('red','LIŻ SIE Z KIMŚ PRZEZ DOPÓKI DRUGA OSOBA NIE BĘDZIE CHCIAŁA "
            "PRESTAĆ')")
cur.execute("insert into Cards(Color,Value) values ('red','OPOWIEDZ COS WSTYDLIWEGO O SOBIE')")
cur.execute("insert into Cards(Color,Value) values ('red','POLIŻ KOMUŚ KROCZE')")
cur.execute("insert into Cards(Color,Value) values ('red','NARYSUJ SOBIE TRAMP STAMP')")
cur.execute("insert into Cards(Color,Value) values ('red','WŁÓŻ LÓD DO KOGOŚ MAJTEK')")
cur.execute("insert into Cards(Color,Value) values ('red','ROZBIERZ SIE DO BIELIZNY')")
cur.execute("insert into Cards(Color,Value) values ('red','POZWÓL SOBIE UCIĄĆ KAWAŁEK WŁOSÓW')")
cur.execute("insert into Cards(Color,Value) values ('red','NAPISZ DO SWOJEGO EX “I MISS U” JEŚLI NIE MASZ PIJ "
            "SAMOTNA KURWO')")
cur.execute("insert into Cards(Color,Value) values ('red','PIJ 3 SHOTY')")
cur.execute("insert into Cards(Color,Value) values ('red','WYMIEŃ SIE ŚLINĄ Z LOSOWĄ OSOBĄ')")
cur.execute("insert into Cards(Color,Value) values ('red','WŁÓŻ SOBIE LÓD MIĘDZY POŚLADKI')")
cur.execute("insert into Cards(Color,Value) values ('red','NASTĘPNE WYZWANIE WYKONUJĄ WSZYSCY GRACZE')")
cur.execute("insert into Cards(Color,Value) values ('red','WYŚLIJ PORNOSA OSOBIE Z RODZINY')")
cur.execute("insert into Cards(Color,Value) values ('red','ZRÓB SPICY ZDJ I WYŚLIJ WSZYSTKIM GRACZOM')")
cur.execute("insert into Cards(Color,Value) values ('black','ROZBIERZ SIE DO NAGA')")
cur.execute("insert into Cards(Color,Value) values ('black','ZŁAP KOMUŚ KROCZE')")
cur.execute("insert into Cards(Color,Value) values ('black','WYŚLIJ DICK / TIT PIC LOSOWEJ OSOBIE')")
cur.execute("insert into Cards(Color,Value) values ('black','JEBNIJ 5 SHOTÓW')")
cur.execute("insert into Cards(Color,Value) values ('black','DRY HUMP LOSOWA OSOBĘ')")
cur.execute("insert into Cards(Color,Value) values ('black','POMACAJ KROCZE / PIERSI LOSOWEJ OSOBIE')")
cur.execute("insert into Cards(Color,Value) values ('black','LIZ SIE Z KIMŚ NA NAGRANIE')")
cur.execute("insert into Cards(Color,Value) values ('black','POKAZ GOŁĄ DUPE')")
cur.execute("insert into Cards(Color,Value) values ('black','POWIEDZ JAK DUŻEGO MASZ')")
cur.execute("insert into Cards(Color,Value) values ('black','NAPISZ DO RODZICÓW JE JESTEŚ GEJEM')")
cur.execute("insert into Cards(Color,Value) values ('black','POLIŻ KOMUSZ CYCKI / DUPE')")
con.commit()